### ISSUE TITLE
Upgrade the Treadmill code base to Python 3

### ISSUE THREAD

**Issue by snyaggarwal** [ThoughtWorksInc/treadmill#7]
So that : 
So that we can future-proof the platform
Tasks: 
"Upgrade the codebase to 3.4
Upgrade the project dependencies to 3.4
Ensure all broken tests are fixed as a result of the upgrade.
Ensure the 3.4 CI pipeline is green.

"
"Risk:
It may be longer running branch where it becomes harder to parallelize the individual tasks
Dependency:
Ensure requirements can successfully upgrade to be compatible with Python 3.4
Assumption:
We can largely automate the transition from 2.7 to 3.4 using tools, like 2to3. [1]
We refer to compatible idioms to ensure untested code paths work as expected [2]

[1] https://docs.python.org/2/library/2to3.html
[2] http://python-future.org/compatible_idioms.html"

**Comment by snyaggarwal** [comment]
**Tasks:**

- [x] Verify python dependencies
- [x] Run 2to3 to update syntax
- [x] Verify things using tox (tests)
- [x] Run treadmill node and container manually
- [ ] Document it.
